import { writable } from 'svelte/store';
export const mapConfig = writable({
  "title": "What is the status of the transposition of the REDIII in the EU?",
  "subtitle": "By November 2025 6 out of 27 EU member states have transposed REDIII partially or fully.",
  "colourSchemeClasses": 5,
  "data": "country,id,value,extraInfo,text_content,link_text,link_url_target,audio_url_1,audio_url_2,audio_url_3,image_url_source,image_url_target,video_url\nAustria,AT,0,true,Nothing,,,,,,,,\nBelgium,BE,0.25,true,Published draft legislation,,,,,,,,\nBulgaria,BG,-0,true,Nothing,,,,,,,,\nCyprus,CY,0,FALSE,,,,,,,,,\nCzechia,CZ,1,true,Transposed both industry and transport targets,,,,,,,,\nGermany,DE,0.25,true,Published draft legislation,,,,,,,,\nDenmark,DK,0.5,true,Transposed only transport,,,,,,,,\nEstonia,EE,0,true,Nothing,,,,,,,,\nGreece,EL,0,true,Nothing,,,,,,,,\nSpain,ES,0.25,true,Published draft legislation,,,,,,,,\nFinland,FI,0.5,true,Transposed only transport,,,,,,,,\nFrance,FR,0.25,true,Published draft legislation,,,,,,,,\nCroatia,HR,0.000,true,Nothing,,,,,,,,\nHungary,HU,1,true,Transposed both industry and transport targets,,,,,,,,\nIreland,IE,0,true,Nothing,,,,,,,,\nItaly,IT,0.25,true,Published draft legislation,,,,,,,,\nLithuania,LT,1,true,Transposed both industry and transport targets,,,,,,,,\nLuxembourg,LU,0,true,Nothing,,,,,,,,\nLatvia,LV,0,true,Nothing,,,,,,,,\nMalta,MT,0,true,Nothing,,,,,,,,\nNetherlands,NL,0.25,true,Published draft legislation,,,,,,,,\nPoland,PL,0,true,Nothing,,,,,,,,\nPortugal,PT,0.25,true,Published draft legislation,,,,,,,,\nRomania,RO,1,true,Transposed both industry and transport targets,,,,,,,,\nSweden,SE,0,true,Nothing,,,,,,,,\nSlovenia,SI,-0,true,Nothing,,,,,,,,\nSlovakia,SK,0,true,Nothing,,,,,,,,",
  "parsedData": [
    {
      "country": "Austria",
      "id": "AT",
      "value": 0,
      "extraInfo": true,
      "text_content": "Nothing",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Belgium",
      "id": "BE",
      "value": 0.25,
      "extraInfo": true,
      "text_content": "Published draft legislation",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Bulgaria",
      "id": "BG",
      "value": 0,
      "extraInfo": true,
      "text_content": "Nothing",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Cyprus",
      "id": "CY",
      "value": 0,
      "extraInfo": false,
      "text_content": "",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Czechia",
      "id": "CZ",
      "value": 1,
      "extraInfo": true,
      "text_content": "Transposed both industry and transport targets",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Germany",
      "id": "DE",
      "value": 0.25,
      "extraInfo": true,
      "text_content": "Published draft legislation",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Denmark",
      "id": "DK",
      "value": 0.5,
      "extraInfo": true,
      "text_content": "Transposed only transport",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Estonia",
      "id": "EE",
      "value": 0,
      "extraInfo": true,
      "text_content": "Nothing",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Greece",
      "id": "EL",
      "value": 0,
      "extraInfo": true,
      "text_content": "Nothing",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Spain",
      "id": "ES",
      "value": 0.25,
      "extraInfo": true,
      "text_content": "Published draft legislation",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Finland",
      "id": "FI",
      "value": 0.5,
      "extraInfo": true,
      "text_content": "Transposed only transport",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "France",
      "id": "FR",
      "value": 0.25,
      "extraInfo": true,
      "text_content": "Published draft legislation",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Croatia",
      "id": "HR",
      "value": 0,
      "extraInfo": true,
      "text_content": "Nothing",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Hungary",
      "id": "HU",
      "value": 1,
      "extraInfo": true,
      "text_content": "Transposed both industry and transport targets",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Ireland",
      "id": "IE",
      "value": 0,
      "extraInfo": true,
      "text_content": "Nothing",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Italy",
      "id": "IT",
      "value": 0.25,
      "extraInfo": true,
      "text_content": "Published draft legislation",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Lithuania",
      "id": "LT",
      "value": 1,
      "extraInfo": true,
      "text_content": "Transposed both industry and transport targets",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Luxembourg",
      "id": "LU",
      "value": 0,
      "extraInfo": true,
      "text_content": "Nothing",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Latvia",
      "id": "LV",
      "value": 0,
      "extraInfo": true,
      "text_content": "Nothing",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Malta",
      "id": "MT",
      "value": 0,
      "extraInfo": true,
      "text_content": "Nothing",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Netherlands",
      "id": "NL",
      "value": 0.25,
      "extraInfo": true,
      "text_content": "Published draft legislation",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Poland",
      "id": "PL",
      "value": 0,
      "extraInfo": true,
      "text_content": "Nothing",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Portugal",
      "id": "PT",
      "value": 0.25,
      "extraInfo": true,
      "text_content": "Published draft legislation",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Romania",
      "id": "RO",
      "value": 1,
      "extraInfo": true,
      "text_content": "Transposed both industry and transport targets",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Sweden",
      "id": "SE",
      "value": 0,
      "extraInfo": true,
      "text_content": "Nothing",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Slovenia",
      "id": "SI",
      "value": 0,
      "extraInfo": true,
      "text_content": "Nothing",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Slovakia",
      "id": "SK",
      "value": 0,
      "extraInfo": true,
      "text_content": "Nothing",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    }
  ],
  "datasetType": "values",
  "datasetUnit": "percent",
  "percentRounded": false,
  "colourSchemeType": "sequential",
  "colourScheme": "green",
  "colourSchemeReverse": false,
  "headlineAvailable": true,
  "subheadlineAvailable": true,
  "tooltipAvailable": false,
  "scaleBarAvailable": false,
  "overrideScaleValues": false,
  "legendAvailable": true,
  "textSourceAvailable": true,
  "textSourceDescription": "Source",
  "textSource": "Hydrogen Europe",
  "textNoteAvailable": true,
  "textNoteDescription": "Note",
  "textNote": "REDIII stands for Renewable Energy Directive III in which a revision was conducted with the result that the cross-sectoral target for the use of renewable energies in the EU by 2030 has to be significantly increased.",
  "textDataAccessAvailable": true,
  "linkDataAccessDescription": "Access the data",
  "linkDataAccess": "https://hydrogeneurope.eu/",
  "legend1": "No data available",
  "legend1Color": "#E0E0E0",
  "customUnitLabelAvailable": false,
  "customUnitLabel": "",
  "tooltipExtraInfoLabel": "Click here",
  "translate": {
    "title": "What is the status of the transposition of the REDIII in the EU?",
    "subtitle": "By November 2025 6 out of 27 EU member states have transposed REDIII partially or fully.",
    "textNoteDescription": "Note",
    "textNote": "REDIII stands for Renewable Energy Directive III in which a revision was conducted with the result that the cross-sectoral target for the use of renewable energies in the EU by 2030 has to be significantly increased.",
    "textSourceDescription": "Source",
    "textSource": "Hydrogen Europe",
    "linkDataAccessDescription": "Access the data",
    "legend1": "No data available",
    "tooltipExtraInfoLabel": "Click here",
    "extraInfo_AT": "Nothing",
    "extraInfo_BE": "Published draft legislation",
    "extraInfo_BG": "Nothing",
    "extraInfo_CZ": "Transposed both industry and transport targets",
    "extraInfo_DE": "Published draft legislation",
    "extraInfo_DK": "Transposed only transport",
    "extraInfo_EE": "Nothing",
    "extraInfo_EL": "Nothing",
    "extraInfo_ES": "Published draft legislation",
    "extraInfo_FI": "Transposed only transport",
    "extraInfo_FR": "Published draft legislation",
    "extraInfo_HR": "Nothing",
    "extraInfo_HU": "Transposed both industry and transport targets",
    "extraInfo_IE": "Nothing",
    "extraInfo_IT": "Published draft legislation",
    "extraInfo_LT": "Transposed both industry and transport targets",
    "extraInfo_LU": "Nothing",
    "extraInfo_LV": "Nothing",
    "extraInfo_MT": "Nothing",
    "extraInfo_NL": "Published draft legislation",
    "extraInfo_PL": "Nothing",
    "extraInfo_PT": "Published draft legislation",
    "extraInfo_RO": "Transposed both industry and transport targets",
    "extraInfo_SE": "Nothing",
    "extraInfo_SI": "Nothing",
    "extraInfo_SK": "Nothing"
  },
  "clusters": [],
  "colorScale": null,
  "extraInfo_AT": "Nothing",
  "extraInfo_BE": "Published draft legislation",
  "extraInfo_BG": "Nothing",
  "extraInfo_CZ": "Transposed both industry and transport targets",
  "extraInfo_DE": "Published draft legislation",
  "extraInfo_DK": "Transposed only transport",
  "extraInfo_EE": "Nothing",
  "extraInfo_EL": "Nothing",
  "extraInfo_ES": "Published draft legislation",
  "extraInfo_FI": "Transposed only transport",
  "extraInfo_FR": "Published draft legislation",
  "extraInfo_HR": "Nothing",
  "extraInfo_HU": "Transposed both industry and transport targets",
  "extraInfo_IE": "Nothing",
  "extraInfo_IT": "Published draft legislation",
  "extraInfo_LT": "Transposed both industry and transport targets",
  "extraInfo_LU": "Nothing",
  "extraInfo_LV": "Nothing",
  "extraInfo_MT": "Nothing",
  "extraInfo_NL": "Published draft legislation",
  "extraInfo_PL": "Nothing",
  "extraInfo_PT": "Published draft legislation",
  "extraInfo_RO": "Transposed both industry and transport targets",
  "extraInfo_SE": "Nothing",
  "extraInfo_SI": "Nothing",
  "extraInfo_SK": "Nothing"
});